font:
  normal:
    family: Liberation Mono
    style: Regular

  size: 9.0

items:
  - colors:
      name: 3024 (dark)
      author: Chris Kempson
      primary:
        background: "#090300"
        foreground: "#a5a2a2"
      cursor:
        text: "#090300"
        cursor: "#a5a2a2"
      normal:
        black: "#090300"
        red: "#db2d20"
        green: "#01a252"
        yellow: "#fded02"
        blue: "#01a0e4"
        magenta: "#a16a94"
        cyan: "#b5e4f4"
        white: "#a5a2a2"
      bright:
        black: "#5c5855"
        red: "#db2d20"
        green: "#01a252"
        yellow: "#fded02"
        blue: "#01a0e4"
        magenta: "#a16a94"
        cyan: "#b5e4f4"
        white: "#f7f7f7"
  - theme: 3024.dark
colors:
  # Default colors
  primary:
    background: '#000000'
    foreground: '#ffffff'

  cursor:
    text: '#ffffff'
    cursor: '#ffffff'

  # Normal colors
  normal:
    black: '#4e4e4e'
    red: '#ff6c60'
    green: '#a8ff60'
    yellow: '#ffffb6'
    blue: '#96cbfe'
    magenta: '#ff73fd'
    cyan: '#c6c5fe'
    white: '#eeeeee'

  # Bright colors
  bright:
    black: '#7c7c7c'
    red: '#ffb6b0'
    green: '#ceffab'
    yellow: '#ffffcb'
    blue: '#b5dcfe'
    magenta: '#ff9cfe'
    cyan: '#dfdffe'
    white: '#ffffff'
theme: IR-Black
