font:
  normal:
    family: Liberation Mono
    style: Regular

  size: 9.0

items:
  - colors:
      name: 3024 (dark)
      author: Chris Kempson
      primary:
        background: "#090300"
        foreground: "#a5a2a2"
      cursor:
        text: "#090300"
        cursor: "#a5a2a2"
      normal:
        black: "#090300"
        red: "#db2d20"
        green: "#01a252"
        yellow: "#fded02"
        blue: "#01a0e4"
        magenta: "#a16a94"
        cyan: "#b5e4f4"
        white: "#a5a2a2"
      bright:
        black: "#5c5855"
        red: "#db2d20"
        green: "#01a252"
        yellow: "#fded02"
        blue: "#01a0e4"
        magenta: "#a16a94"
        cyan: "#b5e4f4"
        white: "#f7f7f7"
  - theme: 3024.dark
colors:
  name: Erebus
  author: ""
  primary:
    background: "#000000"
    foreground: "#ffffff"
  cursor:
    text: "#000000"
    cursor: "#ffffff"
  normal:
    black: "#757575"
    red: "#ff5f5f"
    green: "#de8a36"
    yellow: "#d78787"
    blue: "#af5fd7"
    magenta: "#ff87d7"
    cyan: "#dea3e5"
    white: "#b8b8b8"
  bright:
    black: "#b8b8b8"
    red: "#d78787"
    green: "#ff9f6f"
    yellow: "#ff5f5f"
    blue: "#dea3e5"
    magenta: "#d7afaf"
    cyan: "#af5fd7"
    white: "#757575"
theme: Erebus
